### ISSUE TITLE
EC103 ** wildcard validation is not correct

### ISSUE THREAD

**Issue by stijnherreman** [madskristensen/EditorConfigLanguage#47]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.17.237

### Description
EC103 validation wants you to use `**/*.foo` to match files in subfolders, while the spec says `**.foo` should work, and it does work.

> ** Matches any string of characters

### Steps to recreate
Have the following file structure:

```
.editorconfig
foo\bar\baz.cs
```

Have the following `.editorconfig`:

```
root = true

[foo/**.cs]
indent_style = space
indent_size = 10
```

### Current behavior
EC103 appears, saying the pattern doesn't match any file, even though formatting is applied to `baz.cs`.

### Expected behavior
EC103 should not appear.

**Comment by FurkanKambay** [comment]
It looks like the method returns `false` here: [`EditorConfigValidatorRules.cs:281`]

Calls: [`SLaks/Minimatch/Minimatcher.cs:65`]

## Edit
Looks like any `*` character gets replaced by `[^/]*?` because the method just works char-by-char:
[`SLaks/Minimatch/Minimatcher.cs:L495`] (the action is called from `for`>`switch` below)

And note that this library was ported directly from [the JS library](/isaacs/minimatch) which apparently has the same issue: isaacs/minimatch#67

## Edit 2

[editorconfig-core-js] does this before calling `minimatch`: [`editorconfig-core-js/index.ts:49`]

It's a pretty easy solution but not a perfect one. This way, `**` matches 3 level subdirectories at maximum (`**/**/**`). Should we do that?

[editorconfig-core-js]: /editorconfig/editorconfig-core-js
[`EditorConfigValidatorRules.cs:281`]: /madskristensen/EditorConfigLanguage/blob/46a42b46621d1b691d7f0e9ca9bb8479996dabba/src/Validation/EditorConfigValidatorRules.cs#L281
[`SLaks/Minimatch/Minimatcher.cs:65`]: /SLaks/Minimatch/blob/5a5bd62444005689d8ba71541ac36dcfc775e0c7/Minimatch/Minimatcher.cs#L65
[`SLaks/Minimatch/Minimatcher.cs:L495`]: /SLaks/Minimatch/blob/5a5bd62444005689d8ba71541ac36dcfc775e0c7/Minimatch/Minimatcher.cs#L495
[`editorconfig-core-js/index.ts:49`]: https://github.com/editorconfig/editorconfig-core-js/blob/188a8e4bda06f2653557fa28c8bacc549e10645b/src/index.ts#L49
